### PR TITLE
Fix jwt leak when logging in/out

### LINKED ISSUE #99: API data is not refreshed when logging in and out
We should refresh all of the API data in the onResume() function of each Fragment so that we avoid situations like logging into admin and then logging into non-admin, but still having admin data.

### PR DESCRIPTION
**Pull request by patrickfeltes**
Fixes #99 

Example issue:
Logging out of a staff account and into guest account (in the same app session) still shows staff member's QR code.

There were two issues:
- JWT was not cleared from API singleton object on logout, so incorrect JWT present when logging out and then in during a single app session
- Current API singleton instance captured when passing `apiCall` to a `GenericRepository` (thus holding the old JWT even if it has been cleared on logout)

### CODE REVIEW

File: app/src/main/java/org/hackillinois/android/view/MainActivity.kt [hunk 1]
```diff
@@ -167,6 +167,7 @@ class MainActivity : AppCompatActivity() {
 
         thread {
             App.database.clearAllTables()
+            App.getAPI("")
```
Comment (bstrauch24) [inline app/src/main/java/org/hackillinois/android/view/MainActivity.kt]: This seems like a good thing to be doing :)

**Comment by patrickfeltes** [comment]
> I assume that before, someone could log in with an account, log in later as guest, and keep their token?

Exactly
