### PR TITLE
Fix upcoming event bug

### LINKED ISSUE #198: Upcoming events refresh bug
When an event goes from upcoming -> ongoing, pulling refresh will not update it correctly. Navigating away from the fragment and coming back will, however.

### PR DESCRIPTION
**Pull request by patrickfeltes**
Fixes #198

### CODE REVIEW

File: app/src/main/java/org/hackillinois/android/viewmodel/HomeViewModel.kt [hunk 1]
```diff
@@ -11,13 +13,19 @@ class HomeViewModel : ViewModel() {
...
     fun init() {
-        ongoingEventsLiveData = eventRepository.fetchEventsHappeningAtTime(System.currentTimeMillis())
-        upcomingEventsLiveData = eventRepository.fetchEventsHappeningInNextHour()
+        ongoingEventsLiveData = Transformations.switchMap(currentTime) {
+            value -> eventRepository.fetchEventsHappeningAtTime(value)
+        }
+        upcomingEventsLiveData = Transformations.switchMap(currentTime) {
+            value -> eventRepository.fetchEventsHappeningInNextHour(value)
+        }
+        currentTime.value = System.currentTimeMillis()
```
Comment (bstrauch24) [inline app/src/main/java/org/hackillinois/android/viewmodel/HomeViewModel.kt]: You could call refresh() here, in case you want to change what refresh does in the future

Comment (patrickfeltes) [reply app/src/main/java/org/hackillinois/android/viewmodel/HomeViewModel.kt]: Oh yeah good call
